version: '3.8'

services:
  web:
    container_name: rd-web
    image: ghcr.io/RedCrafter07/deploy/web
    restart: always
    environment:
      PROXY: false
  cm:
    container_name: rd-cm
    image: ghcr.io/RedCrafter07/deploy/cm
    restart: always
  db:
    container_name: rd-db
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: reddeploy
      MONGO_INITDB_ROOT_PASSWORD: '{{INSERT}}'
    command: mongod --auth
