version: '3.8'

services:
  web:
    container_name: rd-web
    image: ghcr.io/RedCrafter07/deploy/web
    restart: always
    environment:
      PROXY: true
  cm:
    container_name: rd-cm
    image: ghcr.io/RedCrafter07/deploy/cm
    restart: always
  db:
    container_name: rd-db
    image: mongo:4.2.17
    restart: always
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: reddeploy
      MONGO_INITDB_ROOT_PASSWORD: '{{INSERT}}'
    command: mongod --auth
  proxy:
    container_name: rd-proxy
    image: ghcr.io/RedCrafter07/deploy/proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      USE_NPM: false

volumes:
  db:
